09 . Arquitetura e Projeto/PedidosJa/PedidosJa/Controllers/PedidoController.cs
using Model.Models;
using Negocio.Business;
using System;
using System.Collections.Generic;
using System.Web.Mvc;


namespace PedidosJa.Controllers
{
    public class PedidoController : Controller
    {
        // GET: Pedido
        public ActionResult ListaDePedidos()
        {
            GerenciadoraPedido rp = new GerenciadoraPedido();
            Empresa empresa = (Empresa)Util.SessionHelper.Get(Util.SessionKeys.EMPRESA);
            List<Pedido> listaPedidos = rp.ObterPedidos(p => p.Empresa.Id == empresa.Id);
            int t = rp.ObterTodos().Count;
            return View(listaPedidos);
        }

        // GET: Pedido
        public ActionResult ListaDePedidosUsuario()
        {
            GerenciadoraPedido rp = new GerenciadoraPedido();
            Usuario usuario = (Usuario)Util.SessionHelper.Get(Util.SessionKeys.USUARIO);
            List<Pedido> listaPedidos = rp.ObterPedidos(p => p.Usuario.Id == usuario.Id);

            return View(listaPedidos);
        }

        public ActionResult AlterarStatusPedido(int id)
        {
            GerenciadoraPedido gp = new GerenciadoraPedido();
            Pedido pedido = gp.Obter(ped => ped.Id == id);
            pedido.Situacao = "Feito";
            gp.Editar(pedido);

            return RedirectToAction("ListaDePedidos");
        }

        //DETALHE PARA EMPRESA
        public ActionResult VerPedidoEmpresa(int id)
        {
            GerenciadoraPedido gp = new GerenciadoraPedido();
            Pedido pedido = gp.Obter(p => p.Id == id);

            MontarResumoDeComplementos(pedido);

            return View(pedido);
        }

        //DETALHE PARA USUARIO
        public ActionResult VerPedidoUsuario(int id)
        {
            GerenciadoraPedido gp = new GerenciadoraPedido();
            Pedido pedido = gp.Obter(p => p.Id == id);

            MontarResumoDeComplementos(pedido);

            return View(pedido);
        }

        public void MontarResumoDeComplementos(Pedido pedido)
        {
            ProdutoController pc = new ProdutoController();
            foreach (var produto in pedido.ListaProdutos)
            {
                pc.FormatarComplementos(produto);
            }
        }

        public ActionResult IniciarPedido(int id)
        {
            GerenciadoraEmpresa ge = new GerenciadoraEmpresa();
            GerenciadoraPedido gp = new GerenciadoraPedido();

            Empresa empresa = ge.Obter(e => e.Id == id);
            Usuario usuario = (Usuario)Util.SessionHelper.Get(Util.SessionKeys.USUARIO);

            Pedido pedido = new Pedido();
            pedido.ListaProdutos = new List<Produto>();
            pedido.Usuario = usuario;
            pedido.NomeUsuario = usuario.Nome;
            pedido.TelefoneUsuario = usuario.Telefone;
            pedido.Empresa = empresa;

            Util.SessionHelper.Set(Util.SessionKeys.PEDIDO, pedido);

            return RedirectToAction("SelecionarProdutoPedido", "Produto");
        }

        public ActionResult AdicionarProdutoAoPedido(int id)
        {

            GerenciadoraProduto gp = new GerenciadoraProduto();
            Produto produto = gp.Obter(p => p.Id == id);

            Produto novo = new Produto();
            novo.Id = produto.Id;
            novo.Nome = produto.Nome;
            novo.Preco = produto.Preco;
            novo.ListaComplemento = new List<Complemento>();

            Pedido pedidoAtual = (Pedido)Util.SessionHelper.Get(Util.SessionKeys.PEDIDO);
            pedidoAtual.ListaProdutos.Add(novo);

            Util.SessionHelper.Set(Util.SessionKeys.PRODUTO, novo);

            return RedirectToAction("SelecionarComplementosPedido", "Complemento");
        }


        public ActionResult VerResumo()
        {
            return RedirectToAction("ListarProdutosResumoPedido", "Produto");
        }

        public ActionResult FinalizarPedido()
        {
            GerenciadoraEndereco ge = new GerenciadoraEndereco();
            Usuario user = (Usuario)Util.SessionHelper.Get(Util.SessionKeys.USUARIO);
            List<Endereco> lista = ge.ObterPorUsuario(e => e.Usuario.Id == user.Id);
            List<SelectListItem> itens = new List<SelectListItem>();
            itens.Add(new SelectListItem { Text = "Selecione o endereço ...", Value = "0", Selected = true });
            for (int i = 0; i < lista.Count; i++)
            {
                itens.Add(new SelectListItem { Text = lista[i].Apelido, Value = "" + lista[i].Id });
            }
            ViewBag.Enderecos = itens;
            return View();
        }

        [HttpPost]
        public ActionResult FinalizarPedido(FormCollection form)
        {
            if (String.Compare(form["Enderecos"], "0") == 0) return RedirectToAction("ListarProdutosResumoPedido", "Produto");
            GerenciadoraEndereco ge = new GerenciadoraEndereco();
            Endereco endereco = ge.Obter(e => e.Id == Int32.Parse(form["Enderecos"]));

            Pedido pedido = (Pedido)Util.SessionHelper.Get(Util.SessionKeys.PEDIDO);
            pedido.DescricaoPagamento = "A vista";
            pedido.Data = DateTime.Now;
            pedido.EnderecoUsuario = endereco.Nome + " - " + endereco.Numero;
            pedido.Situacao = "A fazer";

            GerenciadoraPedido gp = new GerenciadoraPedido();
            gp.Adicionar(pedido);

            Util.SessionHelper.Set(Util.SessionKeys.PEDIDO, null);

            return RedirectToAction("ListaDeEmpresas", "Empresa");
        }
    }
}

09 . Arquitetura e Projeto/PedidosJa/PedidosJa/Controllers/ProdutoController.cs
using Model.Models;
using Negocio.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PedidosJa.Controllers
{
    public class ProdutoController : Controller
    {
        // GET: Produto
        public ActionResult ListaDeProdutos()
        {
            //LIMPAR SEÇÃO DE PRODUTO
            Util.SessionHelper.Set(Util.SessionKeys.PRODUTO, null);

            GerenciadoraProduto gp = new GerenciadoraProduto();
            Empresa empresa = (Empresa) Util.SessionHelper.Get(Util.SessionKeys.EMPRESA);
            List<Produto> listaProdutos = gp.ObterPorEmpresa(e => e.Empresa.Id == empresa.Id);
            return View(listaProdutos);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Produto novoProduto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    novoProduto.ListaComplemento = new List<Complemento>();
                    novoProduto.Empresa = (Empresa)Util.SessionHelper.Get(Util.SessionKeys.EMPRESA);

                    GerenciadoraProduto gp = new GerenciadoraProduto();
                    novoProduto = gp.Adicionar(novoProduto);
                    Util.SessionHelper.Set(Util.SessionKeys.PRODUTO,novoProduto);
                    
                    return RedirectToAction("SelecionarComplementosNovoProduto","Complemento");
                }
            }
            catch
            {

            }
            
            return View();
        }

        public ActionResult Remover(int id)
        {
            GerenciadoraProduto gp = new GerenciadoraProduto();
            Produto prod = gp.Obter(p => p.Id == id);
            gp.Remover(prod);
            return RedirectToAction("ListaDeProdutos", "Produto");
        }

        public ActionResult Alterar(int id)
        {
            GerenciadoraProduto gp = new GerenciadoraProduto();
            Produto prod = gp.Obter(p => p.Id == id);
            return View(prod);
        }
        
        [HttpPost]
        public ActionResult Alterar(Produto prod)
        {
            // Retrieve existing dinner
            GerenciadoraProduto gp = new GerenciadoraProduto();
            Produto prodAlt = gp.Obter(p => p.Id == prod.Id);
            prodAlt.Nome = prod.Nome;
            prodAlt.Preco = prod.Preco;
            gp.Editar(prodAlt);

            Util.SessionHelper.Set(Util.SessionKeys.PRODUTO, prodAlt);
            return RedirectToAction("SelecionarComplementosAlterarProduto", "Complemento");
        }

        public void FormatarComplementos(Produto produto)
        {
            string linha = "";
            foreach (var comp in produto.ListaComplemento)
            {
                linha = comp.Descricao + " | ";
            }
            produto.ComplementosFormatados = linha;
        }
        
        public ActionResult SelecionarProdutoPedido()
        {
            GerenciadoraProduto gp = new GerenciadoraProduto();
            Pedido pedido = (Pedido)Util.SessionHelper.Get(Util.SessionKeys.PEDIDO);
            Empresa empresa = pedido.Empresa;
            List<Produto> listaProdutos = gp.ObterPorEmpresa(p => p.Empresa.Id == empresa.Id);

            ViewBag.QntdItens = pedido.ListaProdutos.Count;

            return View(listaProdutos);
        }
        
        public ActionResult ListarProdutosResumoPedido()
        {
            Pedido pedido = (Pedido)Util.SessionHelper.Get(Util.SessionKeys.PEDIDO);
            float total = 0f;
            if (pedido.ListaProdutos.Count > 0) 
                foreach (Produto p in pedido.ListaProdutos)
                {
                    total += p.Preco;
                }
            ViewBag.Total = total;
            return View(pedido.ListaProdutos);
        }
    }
}

09 . Arquitetura e Projeto/PedidosJa/PedidosJa/Views/Produto/Alterar.cshtml
@model Model.Models.Produto

@{
    ViewBag.Title = "Alterar";
}

<h2>Alterar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Selecionar Complementos" class="btn btn-default" />
            </div>
        </div>
    </div>
}

09 . Arquitetura e Projeto/PedidosJa/PedidosJa/Views/Produto/Create.cshtml
@model Model.Models.Produto

@{
    ViewBag.Title = "Novo Produto";
}

<h2>Novo Produto</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar Produto" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à lista de Produtos", "ListaDeProdutos")
</div>

09 . Arquitetura e Projeto/PedidosJa/PedidosJa/Views/Produto/ListaDeProdutos.cshtml
@model IEnumerable<Model.Models.Produto>

@{
    ViewBag.Title = "Lista de Produtos";
}

<h2>Lista de Produtos</h2>

<p>
    @Html.ActionLink("Novo Produto", "Create")
</p>

    @{
        WebGrid produtos = new WebGrid(source: Model, canPage: true, canSort: true);
        @produtos.GetHtml(
         displayHeader: true,
         fillEmptyRows: true,
         emptyRowCellValue: "---",
         mode: WebGridPagerModes.All,
         numericLinksCount: 2,
         tableStyle: "table",
         columns: produtos.Columns(
             produtos.Column("Nome", "Nome"),
             produtos.Column("Preco", "Preço"),
             produtos.Column(null, null, canSort: false,
                format: (item) => new HtmlString(String.Format("{0} | {1}", new object[] {
                    Html.ActionLink("Alterar", "Alterar", new { id=item.Id }).ToString(),
                    Html.ActionLink("Remover", "Remover", new { id=item.Id }).ToString()
                }))
              )
            )
    );
    }

09 . Arquitetura e Projeto/PedidosJa/PedidosJa/Views/Produto/ListarProdutosResumoPedido.cshtml
@model IEnumerable<Model.Models.Produto>

@{
    ViewBag.Title = "Resumo do Pedido";
}

<h2>Resumo do Pedido</h2>

<p>
    @Html.ActionLink("Voltar para lista de produtos", "SelecionarProdutoPedido")
</p>

<p>
    @Html.ActionLink("Finalizar Pedido", "FinalizarPedido", "Pedido")
</p>

<p>
    TOTAL (R$) : @ViewBag.Total
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            Preço Unit. (R$)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
    </tr>
}

</table>

09 . Arquitetura e Projeto/PedidosJa/PedidosJa/Views/Produto/SelecionarProdutoPedido.cshtml
@model IEnumerable<Model.Models.Produto>

@{
    ViewBag.Title = "Selecionar Produtos";
}

<h2>Selecionar Produtos</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.ActionLink("Adicionar ao pedido", "AdicionarProdutoAoPedido", "Pedido", new { id=item.Id },null)
        </td>
    </tr>
}

</table>